
/* const myPromise = new Promise((success, error)=> {
    setTimeout(() => {
        return error('Error');
    }, 5000)
    
}); */

/* myPromise.then(success => {
    console.log(success);
}).catch(error => {
    console.log(error);
}) */
